// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKc2kY6h6RvJndRCUU0IFWaitg3ua50AM',
    appId: '1:696451797455:web:70f3ab9a38590dfeb842ba',
    messagingSenderId: '696451797455',
    projectId: 'anees-a8319',
    authDomain: 'anees-a8319.firebaseapp.com',
    databaseURL: 'https://anees-a8319-default-rtdb.firebaseio.com',
    storageBucket: 'anees-a8319.appspot.com',
    measurementId: 'G-T4EJ3J8L89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGqw1gMPmqxe5KOGnczuEYESvB3BM-DC4',
    appId: '1:696451797455:android:62a735b5dbdd7ceeb842ba',
    messagingSenderId: '696451797455',
    projectId: 'anees-a8319',
    databaseURL: 'https://anees-a8319-default-rtdb.firebaseio.com',
    storageBucket: 'anees-a8319.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU0C4ijM-jlP_bC0PiJPQRcw18AqXTBHY',
    appId: '1:696451797455:ios:1caa6e818dbd1a84b842ba',
    messagingSenderId: '696451797455',
    projectId: 'anees-a8319',
    databaseURL: 'https://anees-a8319-default-rtdb.firebaseio.com',
    storageBucket: 'anees-a8319.appspot.com',
    iosBundleId: 'com.example.anees',
  );
}
