// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfNDUNCMIw_PfpX_7cIkIpds75MuXpo3A',
    appId: '1:936013172449:web:a60dc39f0ae6d573fc31a0',
    messagingSenderId: '936013172449',
    projectId: 'anees-7bc24',
    authDomain: 'anees-7bc24.firebaseapp.com',
    storageBucket: 'anees-7bc24.appspot.com',
    measurementId: 'G-H0W7KYKV40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGgh9HT3qLz_bncG-BXP-QCn9U1dSHRuY',
    appId: '1:936013172449:android:0abc7d717c895aeffc31a0',
    messagingSenderId: '936013172449',
    projectId: 'anees-7bc24',
    storageBucket: 'anees-7bc24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzjRa-6B6t_M8HkNyfWDo_U5AK0al9mus',
    appId: '1:936013172449:ios:9967e5564aa0ed6afc31a0',
    messagingSenderId: '936013172449',
    projectId: 'anees-7bc24',
    storageBucket: 'anees-7bc24.appspot.com',
    iosBundleId: 'com.example.anees',
  );
}
